//! Regression tests using real wire captures from production dongle trace logs.
//!
//! Every packet in this file was captured from a live Wyze Sense dongle and
//! the expected values were independently verified against the Python reference
//! implementation (wyzesense.py) output.
//!
//! Capture files under tests/captures/ are generated by:
//!   python3 tools/extract_packets.py trace.log > tests/captures/session.jsonl

use wyzesense2mqtt_rs::protocol::packet::{Packet, commands, PacketPayload};
use wyzesense2mqtt_rs::protocol::telemetry::{DongleEvent, SensorType};
use wyzesense2mqtt_rs::protocol::sensor::{WyzeSensor, SensorManager};
use serde::Deserialize;
use std::path::Path;

// =============================================================================
// PACKET-LEVEL PARSING — Real captured packets
// =============================================================================

#[test]
fn test_real_capture_inquiry_response() {
    // Source: trace_hidraw0.log line 8
    // Dongle response to Inquiry (0x4327)
    let raw = [0x55, 0xAA, 0x43, 0x04, 0x28, 0x01, 0x01, 0x6F];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 8);
    assert_eq!(pkt.cmd(), commands::CMD_INQUIRY_RESPONSE);
    assert_eq!(pkt.payload_bytes().unwrap(), &[0x01]);
}

#[test]
fn test_real_capture_enr_response() {
    // Source: trace_hidraw0.log line 13
    // Response to GetENR (0x4302) — 16-byte crypto token
    let raw = [
        0x55, 0xAA, 0x43, 0x13, 0x03,
        0x55, 0xFF, 0xEB, 0x67, 0xD8, 0xC5, 0xF8, 0x70,
        0xB9, 0x43, 0xB0, 0x21, 0xCC, 0x02, 0x3E, 0xEC,
        0x0A, 0xC8, // Checksum: verified 0x0AC8
    ];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 23);
    assert_eq!(pkt.cmd(), commands::CMD_ENR_RESPONSE);
    let payload = pkt.payload_bytes().unwrap();
    assert_eq!(payload.len(), 16);
    assert_eq!(payload[0], 0x55); // First byte of ENR token
}

#[test]
fn test_real_capture_mac_response() {
    // Source: trace_hidraw0.log line 19
    // Response to GetMAC (0x4304) — 8-byte ASCII MAC
    let raw = [
        0x55, 0xAA, 0x43, 0x0B, 0x05,
        0x37, 0x37, 0x41, 0x38, 0x35, 0x41, 0x33, 0x36, // "77A85A36"
        0x03, 0x18, // Checksum: verified 0x0318
    ];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 15);
    assert_eq!(pkt.cmd(), commands::CMD_MAC_RESPONSE);
    let mac = std::str::from_utf8(pkt.payload_bytes().unwrap()).unwrap();
    assert_eq!(mac, "77A85A36");
}

#[test]
fn test_real_capture_version_response() {
    // Source: trace_hidraw0.log line 26
    // Response to GetVersion (0x5316) — ASCII version string
    let raw = [
        0x55, 0xAA, 0x53, 0x1D, 0x17,
        0x30, 0x2E, 0x30, 0x2E, 0x30, 0x2E, 0x34, 0x37,
        0x20, 0x56, 0x31, 0x2E, 0x38, 0x20, 0x47, 0x61,
        0x74, 0x65, 0x77, 0x61, 0x79, 0x20, 0x47, 0x57,
        0x33, 0x55,
        0x08, 0x50, // Checksum: verified 0x0850
    ];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 33);
    assert_eq!(pkt.cmd(), commands::CMD_VERSION_RESPONSE);
    let version = std::str::from_utf8(pkt.payload_bytes().unwrap()).unwrap();
    assert_eq!(version, "0.0.0.47 V1.8 Gateway GW3U");
}

#[test]
fn test_real_capture_ack_packet() {
    // Source: trace_hidraw0.log line 26
    // ACK for GetVersion command (0x5316)
    let raw = [0x55, 0xAA, 0x53, 0x16, 0xFF, 0x02, 0x67];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 7);
    assert_eq!(pkt.cmd(), commands::CMD_ASYNC_ACK);
    // ACK payload should be the acknowledged command
    assert_eq!(pkt.payload, wyzesense2mqtt_rs::protocol::packet::PacketPayload::Ack(commands::CMD_GET_VERSION));
}

#[test]
fn test_real_capture_finish_auth_response() {
    // Source: trace_hidraw0.log line 34
    // Response to FinishAuth (0x5314) — empty payload
    let raw = [0x55, 0xAA, 0x53, 0x03, 0x15, 0x01, 0x6A];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 7);
    assert_eq!(pkt.cmd(), commands::CMD_FINISH_AUTH_RESPONSE);
    assert_eq!(pkt.payload_bytes().unwrap().len(), 0);
}

#[test]
fn test_real_capture_sensor_list_item() {
    // Source: trace_hidraw0.log line 49
    // Sensor list item (0x5331) — 8-byte ASCII MAC
    let raw = [
        0x55, 0xAA, 0x53, 0x0B, 0x31,
        0x37, 0x37, 0x41, 0x38, 0x43, 0x37, 0x39, 0x33, // "77A8C793"
        0x03, 0x5B, // Checksum
    ];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 15);
    assert_eq!(pkt.cmd(), commands::CMD_SENSOR_LIST_ITEM);
    let mac = std::str::from_utf8(pkt.payload_bytes().unwrap()).unwrap();
    assert_eq!(mac, "77A8C793");
}

#[test]
fn test_real_capture_time_sync_request() {
    // Source: trace_hidraw0.log line 60
    // Time Sync Request (0x5332) — empty payload
    let raw = [0x55, 0xAA, 0x53, 0x03, 0x32, 0x01, 0x87];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 7);
    assert_eq!(pkt.cmd(), commands::CMD_TIME_SYNC);
    assert_eq!(pkt.payload_bytes().unwrap().len(), 0);
}

#[test]
fn test_real_capture_time_sync_response_written() {
    // Source: trace_hidraw0.log line 66
    // Time Sync Response (0x5333) written by host
    let raw = [
        0xAA, 0x55, 0x53, 0x0B, 0x33,
        0x00, 0x00, 0x01, 0x9E, 0x6C, 0x59, 0xD9, 0xD3, // 8-byte timestamp
        0x04, 0xA0, // Checksum
    ];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 15);
    assert_eq!(pkt.cmd(), commands::CMD_TIME_SYNC_RESPONSE);
    let payload = pkt.payload_bytes().unwrap();
    assert_eq!(payload.len(), 8);
    // Verify timestamp is a reasonable epoch-ms value
    let ts = u64::from_be_bytes(payload.try_into().unwrap());
    assert!(ts > 1_700_000_000_000); // After 2023
}

// =============================================================================
// TELEMETRY PARSING — Real captured sensor events
// =============================================================================

#[test]
fn test_real_capture_climate_event_21_46c() {
    // Source: trace_cli.log line 10 → "STATE EVENT: MAC=77C68193, Data=Climate { temperature: 21.46, humidity: 48 }"
    // This is the PAYLOAD of a 0x5319 packet (after packet header is stripped)
    let payload = vec![
        0x00, 0x00, 0x01, 0x9E, 0x68, 0xB1, 0x59, 0xEA, // Timestamp
        0xE8, // EVENT_TYPE_CLIMATE
        0x37, 0x37, 0x43, 0x36, 0x38, 0x31, 0x39, 0x33, // MAC: "77C68193"
        0x07, // SensorType: Climate (0x07)
        // Remaining 10 bytes (Climate data format: >BBBBBBBBBB):
        0x15, // [0]: data_type
        0x5F, // [1]: battery = 95%
        0x00, // [2]: unknown
        0x03, // [3]: unknown
        0x15, // [4]: temp_hi = 21
        0x2E, // [5]: temp_lo = 46 → 21.46°C
        0x30, // [6]: humidity = 48%
        0x11, // [7]: unknown
        0x36, // [8]: seq
        0x26, // [9]: RSSI = 38 → -38 dBm
    ];

    let event = DongleEvent::parse_alarm1(&payload).unwrap();
    assert_eq!(event.mac, "77C68193");
    assert_eq!(event.sensor_type, SensorType::ClimateV2);
    
    let mut sensor = WyzeSensor::new(
        event.mac.clone(),
        event.sensor_type,
        "Climate Sensor".to_string(),
    );
    sensor.update_from_event(&event).unwrap();

    // raw 0x5F=95 → 2.97V on 3V coin cell curve → ~87% capacity
    assert_eq!(sensor.battery_pct, Some(87));
    assert_eq!(sensor.rssi_dbm, -38);
    let state = sensor.get_state_payload();
    assert_eq!(state["temperature"], "21.46");
    assert_eq!(state["humidity"], 48);
}

#[test]
fn test_real_capture_climate_event_25_60c() {
    // Source: trace_hidraw0.log line 76-81 → "STATE EVENT: MAC=77C68193, Data=Climate { temperature: 25.6, humidity: 45 }"
    let payload = vec![
        0x00, 0x00, 0x01, 0x9E, 0x6C, 0x5A, 0x81, 0x62, // Timestamp
        0xE8, // EVENT_TYPE_CLIMATE
        0x37, 0x37, 0x43, 0x36, 0x38, 0x31, 0x39, 0x33, // MAC: "77C68193"
        0x07, // SensorType: Climate (0x07)
        0x18, // [0]: data_type
        0x5C, // [1]: battery = 92%
        0x00, // [2]: unknown
        0x03, // [3]: unknown
        0x19, // [4]: temp_hi = 25
        0x3C, // [5]: temp_lo = 60 → 25.60°C
        0x2D, // [6]: humidity = 45%
        0x11, // [7]: unknown
        0x42, // [8]: seq
        0x2F, // [9]: RSSI = 47 → -47 dBm
    ];

    let event = DongleEvent::parse_alarm1(&payload).unwrap();
    assert_eq!(event.mac, "77C68193");
    assert_eq!(event.sensor_type, SensorType::ClimateV2);
    
    let mut sensor = WyzeSensor::new(
        event.mac.clone(),
        event.sensor_type,
        "Climate Sensor".to_string(),
    );
    sensor.update_from_event(&event).unwrap();

    // raw 0x5C=92 → 2.88V on 3V coin cell curve → ~70% capacity
    assert_eq!(sensor.battery_pct, Some(70));
    assert_eq!(sensor.rssi_dbm, -47);
    let state = sensor.get_state_payload();
    assert_eq!(state["temperature"], "25.60");
    assert_eq!(state["humidity"], 45);
}

#[test]
fn test_real_capture_climate_event_24_06c() {
    // Source: trace_cli.log line 18 → "STATE EVENT: MAC=77C68193, Data=Climate { temperature: 24.06, humidity: 48 }"
    let payload = vec![
        0x00, 0x00, 0x01, 0x9E, 0x6C, 0x1F, 0x8D, 0xFE, // Timestamp
        0xE8, // EVENT_TYPE_CLIMATE
        0x37, 0x37, 0x43, 0x36, 0x38, 0x31, 0x39, 0x33, // MAC: "77C68193"
        0x07, // SensorType: Climate
        0x18, // data_type
        0x5F, // battery = 95%
        0x00, // unknown
        0x03, // unknown
        0x18, // temp_hi = 24
        0x06, // temp_lo = 6 → 24.06°C
        0x30, // humidity = 48%
        0x11, // unknown
        0x3F, // seq
        0x2D, // RSSI = 45 → -45 dBm
    ];

    let event = DongleEvent::parse_alarm1(&payload).unwrap();
    assert_eq!(event.mac, "77C68193");
    assert_eq!(event.sensor_type, SensorType::ClimateV2);
    
    let mut sensor = WyzeSensor::new(
        event.mac.clone(),
        event.sensor_type,
        "Climate Sensor".to_string(),
    );
    sensor.update_from_event(&event).unwrap();

    // raw 0x5F=95 → 2.97V on 3V coin cell curve → ~87% capacity
    assert_eq!(sensor.battery_pct, Some(87));
    assert_eq!(sensor.rssi_dbm, -45);
    let state = sensor.get_state_payload();
    assert_eq!(state["temperature"], "24.06");
    assert_eq!(state["humidity"], 48);
}

#[test]
fn test_real_capture_climate_event_25_09c() {
    // Source: trace_cli.log line 125-128 → "STATE EVENT: MAC=77C68193, Data=Climate { temperature: 25.09, humidity: 46 }"
    let payload = vec![
        0x00, 0x00, 0x01, 0x9E, 0x6C, 0x51, 0x60, 0x70, // Timestamp
        0xE8, // EVENT_TYPE_CLIMATE
        0x37, 0x37, 0x43, 0x36, 0x38, 0x31, 0x39, 0x33, // MAC: "77C68193"
        0x07, // SensorType: Climate
        0x18, // data_type
        0x5F, // battery = 95%
        0x00, // unknown
        0x03, // unknown
        0x19, // temp_hi = 25
        0x09, // temp_lo = 9 → 25.09°C
        0x2E, // humidity = 46%
        0x11, // unknown
        0x41, // seq
        0x2D, // RSSI = 45 → -45 dBm
    ];

    let event = DongleEvent::parse_alarm1(&payload).unwrap();
    assert_eq!(event.mac, "77C68193");
    assert_eq!(event.sensor_type, SensorType::ClimateV2);
    
    let mut sensor = WyzeSensor::new(
        event.mac.clone(),
        event.sensor_type,
        "Climate Sensor".to_string(),
    );
    sensor.update_from_event(&event).unwrap();

    // raw 0x5F=95 → 2.97V on 3V coin cell curve → ~87% capacity
    assert_eq!(sensor.battery_pct, Some(87));
    assert_eq!(sensor.rssi_dbm, -45);
    let state = sensor.get_state_payload();
    assert_eq!(state["temperature"], "25.09");
    assert_eq!(state["humidity"], 46);
}

// =============================================================================
// FULL PACKET PARSING — Parse complete wire packet including framing
// =============================================================================

#[test]
fn test_real_capture_full_climate_packet_with_checksum() {
    // Complete 0x5319 packet from trace_hidraw0.log line 76
    // Verified checksum: 0x07F8
    let raw = [
        0x55, 0xAA, 0x53, 0x1F, 0x19,
        0x00, 0x00, 0x01, 0x9E, 0x6C, 0x5A, 0x81, 0x62,
        0xE8, 0x37, 0x37, 0x43, 0x36, 0x38, 0x31, 0x39,
        0x33, 0x07, 0x18, 0x5C, 0x00, 0x03, 0x19, 0x3C,
        0x2D, 0x11, 0x42, 0x2F,
        0x07, 0xF8, // Checksum
    ];

    // Verify packet parses successfully (checksum validated internally)
    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 35); // b2=0x1F=31, total=31+4=35
    assert_eq!(pkt.cmd(), commands::CMD_ALARM1);

    // Now parse the telemetry from the payload
    let payload = pkt.payload_bytes().unwrap();
    let event = DongleEvent::parse_alarm1(payload).unwrap();
    assert_eq!(event.mac, "77C68193");
    assert_eq!(event.sensor_type, SensorType::ClimateV2);
    
    let mut sensor = WyzeSensor::new(
        event.mac.clone(),
        event.sensor_type,
        "Climate Sensor".to_string(),
    );
    sensor.update_from_event(&event).unwrap();

    // raw 0x5C=92 → 2.88V on 3V coin cell curve → ~70% capacity
    assert_eq!(sensor.battery_pct, Some(70));
    assert_eq!(sensor.rssi_dbm, -47);
    let state = sensor.get_state_payload();
    assert_eq!(state["temperature"], "25.60");
    assert_eq!(state["humidity"], 45);
}

#[test]
fn test_real_capture_full_climate_packet_21_46() {
    // Complete 0x5319 packet from trace_cli.log line 10
    // Verified checksum: 0x0887
    let raw = [
        0x55, 0xAA, 0x53, 0x1F, 0x19,
        0x00, 0x00, 0x01, 0x9E, 0x68, 0xB1, 0x59, 0xEA,
        0xE8, 0x37, 0x37, 0x43, 0x36, 0x38, 0x31, 0x39,
        0x33, 0x07, 0x15, 0x5F, 0x00, 0x03, 0x15, 0x2E,
        0x30, 0x11, 0x36, 0x26,
        0x08, 0x87, // Checksum
    ];

    let (pkt, consumed) = Packet::parse(&raw).unwrap();
    assert_eq!(consumed, 35);
    assert_eq!(pkt.cmd(), commands::CMD_ALARM1);

    let payload = pkt.payload_bytes().unwrap();
    let event = DongleEvent::parse_alarm1(payload).unwrap();
    assert_eq!(event.mac, "77C68193");
    assert_eq!(event.sensor_type, SensorType::ClimateV2);
    
    let mut sensor = WyzeSensor::new(
        event.mac.clone(),
        event.sensor_type,
        "Climate Sensor".to_string(),
    );
    sensor.update_from_event(&event).unwrap();

    // raw 0x5F=95 → 2.97V on 3V coin cell curve → ~87% capacity
    assert_eq!(sensor.battery_pct, Some(87));
    assert_eq!(sensor.rssi_dbm, -38);
    let state = sensor.get_state_payload();
    assert_eq!(state["temperature"], "21.46");
    assert_eq!(state["humidity"], 48);
}

// =============================================================================
// MULTI-PACKET STREAM — Parsing multiple packets from a single buffer
// =============================================================================

#[test]
fn test_real_capture_two_packets_concatenated() {
    // Simulates what happens when a large HID frame contains multiple packets.
    // Packet 1: Inquiry Response (8 bytes)
    // Packet 2: Sensor list ACK (7 bytes)
    let stream = [
        // Packet 1: Inquiry Response
        0x55, 0xAA, 0x43, 0x04, 0x28, 0x01, 0x01, 0x6F,
        // Packet 2: ACK for 0x5330
        0x55, 0xAA, 0x53, 0x30, 0xFF, 0x02, 0x81,
    ];

    // Parse first packet
    let (pkt1, consumed1) = Packet::parse(&stream).unwrap();
    assert_eq!(consumed1, 8);
    assert_eq!(pkt1.cmd(), commands::CMD_INQUIRY_RESPONSE);

    // Parse second packet from remaining bytes
    let (pkt2, consumed2) = Packet::parse(&stream[consumed1..]).unwrap();
    assert_eq!(consumed2, 7);
    assert_eq!(pkt2.cmd(), commands::CMD_ASYNC_ACK);
    assert_eq!(pkt2.payload, wyzesense2mqtt_rs::protocol::packet::PacketPayload::Ack(commands::CMD_GET_SENSOR_LIST));
}

#[test]
fn test_parse_fails_on_truncated_packet() {
    // Only first 5 bytes of an 8-byte packet — should fail gracefully
    let truncated = [0x55, 0xAA, 0x43, 0x04, 0x28];

    let result = Packet::parse(&truncated);
    assert!(result.is_err(), "Should fail to parse truncated packet");
}

#[test]
fn test_parse_fails_on_bad_checksum() {
    // Valid structure but wrong checksum (last 2 bytes mangled)
    let bad = [0x55, 0xAA, 0x43, 0x04, 0x28, 0x01, 0xFF, 0xFF];

    let result = Packet::parse(&bad);
    assert!(result.is_err(), "Should fail on bad checksum");
}

#[test]
fn test_real_capture_round_trip_inquiry() {
    // Write inquiry → serialize → parse back → compare
    let original = Packet::new_sync((commands::CMD_INQUIRY & 0xFF) as u8, vec![]);
    let serialized = original.to_bytes();

    // Verify against known wire bytes
    assert_eq!(serialized, vec![0xAA, 0x55, 0x43, 0x03, 0x27, 0x01, 0x6C]);

    // Round-trip parse
    let (parsed, _) = Packet::parse(&serialized).unwrap();
    assert_eq!(parsed.cmd(), original.cmd());
    assert_eq!(parsed.payload_bytes(), original.payload_bytes());
}

#[test]
fn test_real_capture_round_trip_ack() {
    // Construct ACK for 0x5319 → serialize → verify wire format
    let ack = Packet::new_ack(commands::CMD_ALARM1);
    let bytes = ack.to_bytes();

    // Parse back
    let (parsed, consumed) = Packet::parse(&bytes).unwrap();
    assert_eq!(consumed, 7);
    assert_eq!(parsed.payload, wyzesense2mqtt_rs::protocol::packet::PacketPayload::Ack(commands::CMD_ALARM1));
}

// =============================================================================
// CAPTURE FILE LOADING — Parse packets from extracted trace log JSONL files
// =============================================================================

/// A captured I/O record loaded from a JSONL file.
#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct CaptureRecord {
    #[allow(dead_code)]
    ts_ms: u64,
    dir: String,
    proto_hex: String,
    proto_len: usize,
    #[serde(default)]
    raw_hex: Option<String>,
    #[serde(default)]
    raw_len: Option<usize>,
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .filter_map(|i| {
            if i + 2 <= hex.len() {
                u8::from_str_radix(&hex[i..i + 2], 16).ok()
            } else {
                None
            }
        })
        .collect()
}

fn load_capture_file(path: &Path) -> Vec<CaptureRecord> {
    let content = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Failed to load capture file {:?}: {}", path, e));
    content
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(line)
            .unwrap_or_else(|e| panic!("Failed to parse JSONL line: {} -- {}", e, line)))
        .collect()
}

#[test]
fn test_all_captures_in_directory_parseable() {
    let captures_dir = Path::new("tests/captures");
    if !captures_dir.exists() {
        eprintln!("Skipping capture directory tests: {:?} not found", captures_dir);
        return;
    }

    let dir_entries = std::fs::read_dir(captures_dir)
        .unwrap_or_else(|e| panic!("Failed to read captures directory: {}", e));

    let mut tested_files = 0;
    let mut total_records_parsed = 0;
    let mut total_write_roundtrips = 0;

    for entry in dir_entries {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_file() && path.extension().map_or(false, |ext| ext == "jsonl") {
            let filename = path.file_name().unwrap().to_string_lossy().into_owned();
            println!("Testing capture file: {}", filename);

            let records = load_capture_file(&path);
            assert!(!records.is_empty(), "Capture file {} is empty", filename);

            let mut total_parsed = 0;
            let mut total_fragments = 0;
            let mut failures = Vec::new();

            // Setup a test-local SensorManager for visual state checking
            let test_config_path = format!("target/test_sensors_{}.yaml", filename.replace(".", "_"));
            let test_state_path = format!("target/test_state_{}.yaml", filename.replace(".", "_"));
            
            let _ = std::fs::remove_file(&test_config_path);
            let _ = std::fs::remove_file(&test_state_path);

            let mut manager = SensorManager::new(
                test_config_path.clone(),
                test_state_path.clone(),
            );

            for (idx, rec) in records.iter().enumerate() {
                // 1. Verify basic length match
                assert_eq!(rec.proto_hex.len() / 2, rec.proto_len,
                    "Record {}: proto_hex length mismatch in {}", idx, filename);

                // 2. Parse protocol bytes
                let bytes = hex_to_bytes(&rec.proto_hex);
                if bytes.is_empty() {
                    continue;
                }

                let mut offset = 0;
                let mut parsed_in_rec = 0;
                let mut first_err = None;

                while offset < bytes.len() {
                    match Packet::parse(&bytes[offset..]) {
                        Ok((pkt, consumed)) => {
                            offset += consumed;
                            parsed_in_rec += 1;
                            total_parsed += 1;
                            total_records_parsed += 1;

                            // If read from dongle, route events to the SensorManager
                            if rec.dir == "R" {
                                let mut event_opt = None;
                                match pkt.cmd() {
                                    commands::CMD_ALARM1 => {
                                        if let PacketPayload::Bytes(payload) = pkt.payload {
                                            if let Ok(evt) = DongleEvent::parse_alarm1(&payload) {
                                                event_opt = Some(evt);
                                            }
                                        }
                                    }
                                    commands::CMD_ALARM2 => {
                                        if let PacketPayload::Bytes(payload) = pkt.payload {
                                            if let Ok(evt) = DongleEvent::parse_alarm2(&payload) {
                                                event_opt = Some(evt);
                                            }
                                        }
                                    }
                                    commands::CMD_SENSOR_SCAN => {
                                        if let PacketPayload::Bytes(payload) = pkt.payload {
                                            if let Ok(evt) = DongleEvent::parse_scan(&payload) {
                                                event_opt = Some(evt);
                                            }
                                        }
                                    }
                                    _ => {}
                                }

                                if let Some(evt) = event_opt {
                                    if manager.dispatch_event(&evt) {
                                        if let Some(sensor) = manager.get_sensors().get(&evt.mac) {
                                            let payload = sensor.get_state_payload();
                                            println!("  Sensor MAC: {} | State: {}", evt.mac, serde_json::to_string(&payload).unwrap());
                                        }
                                    }
                                }
                            }
                        }
                        Err(e) => {
                            if parsed_in_rec == 0 {
                                first_err = Some(format!("offset {}: {}", offset, e));
                            }
                            break; // remaining bytes may be stale HID data
                        }
                    }
                }

                if parsed_in_rec == 0 {
                    if let Some(e) = first_err {
                        // Records that start with stale HID buffer data (no valid magic) are fragments
                        let magic = if bytes.len() >= 2 { (bytes[0] as u16) << 8 | bytes[1] as u16 } else { 0 };
                        if magic == 0x55AA || magic == 0xAA55 {
                            failures.push((idx, rec.dir.clone(), e));
                        } else {
                            total_fragments += 1;
                        }
                    }
                }

                // 3. If raw_hex is present, verify extract_hid_frame extracts proto_hex exactly!
                if let (Some(raw_hex), Some(raw_len)) = (&rec.raw_hex, rec.raw_len) {
                    let raw_bytes = hex_to_bytes(raw_hex);
                    assert_eq!(raw_bytes.len(), raw_len,
                        "Record {}: raw_hex length mismatch in {}", idx, filename);

                    let mut extracted_buf = vec![0u8; raw_bytes.len() * 2];
                    let extracted_len = wyzesense2mqtt_rs::transport::hidraw::extract_hid_frame(&raw_bytes, &mut extracted_buf);
                    
                    let expected_proto = hex_to_bytes(&rec.proto_hex);
                    assert_eq!(extracted_len, rec.proto_len,
                        "Record {}: extracted proto length mismatch in {}", idx, filename);
                    assert_eq!(&extracted_buf[..extracted_len], &expected_proto,
                        "Record {}: extracted proto bytes mismatch in {}", idx, filename);
                }

                // 4. If it's a write packet, verify round-trip serialization works perfectly!
                if rec.dir == "W" {
                    let bytes = hex_to_bytes(&rec.proto_hex);
                    if let Ok((pkt, consumed)) = Packet::parse(&bytes) {
                        let reserialized = pkt.to_bytes();
                        assert_eq!(reserialized, bytes[..consumed],
                            "Record {}: round-trip serialization mismatch for write packet in {}", idx, filename);
                        total_write_roundtrips += 1;
                    }
                }
            }

            // Visual Sensor State Printer
            println!("\n=======================================================================");
            println!("Consolidated Sensor States for Capture File: {}", filename);
            println!("=======================================================================");
            let sensors = manager.get_sensors();
            if sensors.is_empty() {
                println!("  No sensors discovered in this capture session.");
            } else {
                for (mac, sensor) in sensors {
                    let payload = sensor.get_state_payload();
                    println!("  Sensor MAC: {} | State: {}", mac, serde_json::to_string(&payload).unwrap());
                }
            }
            println!("=======================================================================\n");

            // Clean up temporary files
            let _ = std::fs::remove_file(&test_config_path);
            let _ = std::fs::remove_file(&test_state_path);

            println!("  Success: {} records, {} packets parsed, {} fragments skipped, {} failures",
                records.len(), total_parsed, total_fragments, failures.len());

            for (idx, dir, err) in &failures {
                eprintln!("  FAIL record #{} (dir={}): {}", idx, dir, err);
            }

            assert!(failures.is_empty(),
                "Some records with valid magic failed to parse in {}: {:?}", filename, failures);

            tested_files += 1;
        }
    }

    println!("Capture test run complete. Tested {} files, parsed {} total packets, validated {} write roundtrips.",
        tested_files, total_records_parsed, total_write_roundtrips);
    
    assert!(tested_files > 0, "No capture files (.jsonl) found under tests/captures/");
}


